Import("env")

import hashlib
import os
import subprocess
from pathlib import Path


PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
GENERATED_BUILD_INFO = PROJECT_DIR / "src" / "generated_build_info.h"


def git(*args, fallback="unknown"):
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=PROJECT_DIR,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return fallback


def c_flag_string(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'\\"{value}\\"'


def c_literal(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{value}"'


def write_build_info(version: str, sha: str) -> None:
    content = (
        "#pragma once\n"
        "// Generated by scripts/build_flags.py. Do not commit.\n"
        f"#define HYDRO_GENERATED_VERSION {c_literal(version)}\n"
        f"#define HYDRO_GENERATED_BUILD_SHA {c_literal(sha)}\n"
    )
    try:
        current = GENERATED_BUILD_INFO.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = ""
    if current != content:
        GENERATED_BUILD_INFO.write_text(content, encoding="utf-8")


version = os.getenv("HYDRO_VERSION") or git("describe", "--tags", "--always", "--dirty")
sha = os.getenv("GITHUB_SHA") or git("rev-parse", "HEAD")
sha = sha[:8] if sha and sha != "unknown" else "unknown"
write_build_info(version, sha)

# Only configuration that genuinely changes compilation semantics belongs in
# BUILD_FLAGS. Build/version metadata lives in generated_build_info.h and is
# consumed by one translation unit (version.cpp). Otherwise every new commit SHA
# invalidates the entire Arduino framework cache and turns an incremental build
# into a full rebuild.
flags = []

# Wi-Fi can be injected by hydroctl/install.sh from environment variables or a
# local .env file. WIFI_SEED_ID makes those credentials a one-shot provisioning
# seed: they are copied into NVS once, then later Web UI edits are respected.
ssid = os.getenv("WIFI_SSID", "")
password = os.getenv("WIFI_PASSWORD", "")
if ssid:
    seed_id = os.getenv("WIFI_SEED_ID", "").strip()
    if not seed_id:
        seed_id = hashlib.sha256((ssid + "\0" + password).encode("utf-8")).hexdigest()[:16]
    flags.append(f"-DWIFI_SSID={c_flag_string(ssid)}")
    flags.append(f"-DWIFI_PASSWORD={c_flag_string(password)}")
    flags.append(f"-DWIFI_SEED_ID={c_flag_string(seed_id)}")

tz = os.getenv("TIMEZONE_OFFSET")
if tz:
    try:
        offset = int(tz)
        if -12 <= offset <= 14:
            flags.append(f"-DTIMEZONE_OFFSET={offset}")
    except ValueError:
        print("[build] Ignoring invalid TIMEZONE_OFFSET; expected integer -12..14")

env.Append(BUILD_FLAGS=flags)
print(f"[build] HydroESP-C3 {version} ({sha})")
